### ISSUE TITLE
Modify configure.py to get embedded cd++ route by itself

### ISSUE THREAD

**Issue by plbalbi** [colonelpringles/pringles#17]
We can just remove this step from the setup command and have the config.py as a file in the repo. The file would be something like:

```
import os

CDPP_BIN_PATH = os.getcwd() + '/cdpp/src/bin'
```

This may lead to having the config variables duplicated (once for bash and also for python) so we could make the whole setup script in python.

_Originally posted by @juanlanuzag in https://github.com/colonelpringles/pringles/pull/16_

**Comment by juanlanuzag** [comment]
Solved in [#PR22](https://github.com/colonelpringles/pringles/pull/22)
