### ISSUE TITLE
Generate .ma files from Python

### ISSUE THREAD

**Issue by juanlanuzag** [colonelpringles/pringles#2]

**Comment by plbalbi** [comment]
- Define Atomic, Port, and CoupledModel interfaces
- Make Model to .ma file conversion
- Parametrization
- Topology-based model replication

**Comment by juanlanuzag** [comment]
@plbalbi Do you remember what you meant by "Topology-based model replication"?

**Comment by plbalbi** [comment]
@juanlanuzag yes, kind of, but we should discuss it. 
Simply, I meant that you should be able to, once defined a model, replicate it following some pattern (or topology). 
For example, you could have a model of a power grid, in which you have:
- A power station, which generates the electricity.
- A generic consumer model, which you could replicate and _connect_ to the grid, given some rules of how to connect two consumers together.
Having that, you could make maybe a rectangular-grid, or a ring-like-grid, etc.
