### ISSUE TITLE
Make a cd++ log parser

### ISSUE THREAD

**Issue by juanlanuzag** [colonelpringles/pringles#3]

**Comment by juanlanuzag** [comment]
Basic log parsing is done in SimulationResult, it exposes a pandas Dataframes with the logs. Maybe we can add some extra helper functions but the main part is done

**Comment by juanlanuzag** [comment]
We need to transform the time returned by the simulation to the Duration class and see how to map that class to an axis in matplotlib

**Comment by plbalbi** [comment]
Add custom API. Improve the whole thing.

**Comment by plbalbi** [comment]
We should keep in mind possible API changes / features that could change us while doing the code-as-documentation simulations.
Maybe while doing it, we can iterate the log-parser and the features it provides, and improve it a little.

**Comment by plbalbi** [comment]
This issue should be close, and we should split it as needed, and decide the scope we want to reach.
What do you think @juanlanuzag ?

**Comment by juanlanuzag** [comment]
Yeah, that makes sense, this issue is too general an ambiguous.
