### ISSUE TITLE
Abstract simulator executable control

### ISSUE THREAD

**Issue by plbalbi** [colonelpringles/pringles#6]
From ExecutableDiscoverer return some kind of SimulatorController, which abstracts from the simulation location, or where it lives (as to in some future, abstract a remote version of the simulator).
This also can help to delegate all **simulator binary** control to the this object, and just let the Wrapper handle the parameterization of the simulation, and abstract from system error, network error, etc.

**Comment by juanlanuzag** [comment]
@plbalbi can we close this issue?
