### ISSUE TITLE
requirements.txt and min-python-version are needed.

### ISSUE THREAD

**Issue by plbalbi** [colonelpringles/pringles#7]
Totally agree. A **requirements.txt** and a **minor-python-version** are needed. Will convert this into an issue.

_Originally posted by @plbalbi in https://github.com/colonelpringles/pringles/pull/5/review_comment/create_

**Comment by juanlanuzag** [comment]
Whats the "minor-python-version"? Is it some type of standard file?

**Comment by plbalbi** [comment]
min-python-version, I misspelled.
