### ISSUE TITLE
Add PEP8 and tests automated verification

### ISSUE THREAD

**Issue by plbalbi** [colonelpringles/pringles#9]
Maybe as git hook, to prevent non-verified pushes. Also tests hooks.

PEP 8:
"Imports should be grouped in the following order:
Standard library imports.
Related third party imports.
Local application/library specific imports.
You should put a blank line between each group of imports."

And for subprocess, there should only be one import:
`import subprocess` and using subprocess.CalledProcessError
or
`from subprocess import CalledProcessError,  run`

I prefer the first but both are correct

_Originally posted by @juanlanuzag in https://github.com/colonelpringles/pringles/pull/5_

**Comment by juanlanuzag** [comment]
I don't think pep8 checker should be enforced, a lot of times the errors should be allowed. For example, if you declare an interface in the __init__.py file that isn't yet being used, you would get an  " 'SUBMODULE_NAME' imported but unused" error.

Each developer should have the flake8 checker configured on their editor.

**Comment by juanlanuzag** [comment]
Added in PR #13
